# Generated by Django 4.2.5 on 2023-10-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата(день)')),
                ('target', models.PositiveIntegerField(verbose_name='спрос в ШТ.')),
            ],
            options={
                'verbose_name': 'Ежедневный прогноз продаж',
                'verbose_name_plural': 'Ежедневные прогнозы продаж',
            },
        ),
        migrations.CreateModel(
            name='StoreForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата прогноза')),
            ],
            options={
                'verbose_name': 'Прогноз магазина',
                'verbose_name_plural': 'Прогнозы магазинов',
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('store_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='forecast.storeforecast', verbose_name='Прогноз магазина')),
            ],
            options={
                'verbose_name': 'Закладка прогнозов пользователя',
                'verbose_name_plural': 'Закладки прогнозов пользователей',
            },
        ),
    ]
