# Generated by Django 4.2.5 on 2023-10-08 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата прогноза')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_forecasts', to='categories.category', verbose_name='захэшированное id товара')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stores.store', verbose_name='захэшированное id магазина')),
            ],
            options={
                'verbose_name': 'Прогноз магазина',
                'verbose_name_plural': 'Прогнозы магазинов',
            },
        ),
        migrations.CreateModel(
            name='DailySalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата(день)')),
                ('target', models.PositiveIntegerField(verbose_name='спрос в ШТ.')),
                ('forecast_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_units', to='forecast.storeforecast', verbose_name='Прогноз товара')),
            ],
            options={
                'verbose_name': 'Ежедневный прогноз продаж',
                'verbose_name_plural': 'Ежедневные прогнозы продаж',
            },
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('store_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='forecast.storeforecast', verbose_name='Прогноз магазина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка прогнозов пользователя',
                'verbose_name_plural': 'Закладки прогнозов пользователей',
                'unique_together': {('user', 'store_forecast')},
            },
        ),
    ]
