# Generated by Django 4.2.5 on 2023-09-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SkuForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_forecasts', to='forecast.storeforecast')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_forecasts', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target', models.PositiveIntegerField()),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.skuforecast')),
            ],
        ),
    ]
