# Generated by Django 4.2.5 on 2023-09-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_alter_store_city_and_more'),
        ('categories', '0002_alter_category_options_alter_category_category_and_more'),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysalesforecast',
            options={'verbose_name': 'Ежедневный прогноз продаж', 'verbose_name_plural': 'Ежедневные прогнозы продаж'},
        ),
        migrations.AlterModelOptions(
            name='skuforecast',
            options={'verbose_name': 'Прогноз товара', 'verbose_name_plural': 'Прогнозы товаров'},
        ),
        migrations.AlterModelOptions(
            name='storeforecast',
            options={'verbose_name': 'Прогноз магазина', 'verbose_name_plural': 'Прогнозы магазинов'},
        ),
        migrations.AlterField(
            model_name='dailysalesforecast',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailysalesforecast',
            name='sales_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.skuforecast', verbose_name='Прогноз товара'),
        ),
        migrations.AlterField(
            model_name='dailysalesforecast',
            name='target',
            field=models.PositiveIntegerField(verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='skuforecast',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_forecasts', to='forecast.storeforecast', verbose_name='Прогноз магазина'),
        ),
        migrations.AlterField(
            model_name='skuforecast',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_forecasts', to='categories.category', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='forecast_date',
            field=models.DateField(verbose_name='Дата прогноза'),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stores.store', verbose_name='Магазин'),
        ),
    ]
