# Generated by Django 4.2.5 on 2023-09-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesforecast',
            name='forecast_sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_units', to='forecast.storeforecast', verbose_name='Прогноз товара'),
        ),
    ]
