version: '3.3'
services:
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  backend:
    build: ../backend/
    restart: always
    volumes:
      - static_value:/app/staticfiles/
    # depends_on:
    #   - db
    # env_file:
    #   - ./.env

  # frontend:
  #   image: lenta_frontend:latest
  #   volumes:
  #     - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - /root/LentaHackathon/infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
    depends_on:
       - backend

volumes:
  static_value:
  media_value:
  # postgres_data: