# Generated by Django 4.2.5 on 2023-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('group', 'category', 'subcategory', 'sku'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, verbose_name='захэшированная категория товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(max_length=50, verbose_name='захэшированная группа товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='захэшированное id товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.CharField(max_length=50, verbose_name='захэшированная подкатегория товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.PositiveIntegerField(verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
