# Generated by Django 4.2.5 on 2023-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.IntegerField(choices=[('штука', 'Штука'), ('кг/г', 'кг/u')], verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
