# Generated by Django 4.2.5 on 2023-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('group', 'category', 'subcategory', 'sku'), 'verbose_name': 'Свобная таблица категории', 'verbose_name_plural': 'Свобная таблица категорий'},
        ),
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.CharField(max_length=50, verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
