# Generated by Django 4.2.5 on 2023-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.IntegerField(choices=[(17, 'Штука'), (1, 'Вес')], verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
