# Generated by Django 4.2.5 on 2023-09-27 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('subcategory',), 'verbose_name': 'Субкатегория', 'verbose_name_plural': 'Субкатегории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
