# Generated by Django 4.2.5 on 2023-10-04 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uom',
            field=models.IntegerField(choices=[('штука', 'Штука'), ('вес', 'Вес')], validators=[django.core.validators.MinValueValidator(0)], verbose_name='маркер, обозначающий продаётся товар на вес или в ШТ'),
        ),
    ]
