# Generated by Django 4.2.5 on 2023-09-24 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_sales', to='categories.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_type', models.IntegerField()),
                ('sales_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sales_units_promo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sales_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_rub_promo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='sales.sales')),
            ],
        ),
    ]
