# Generated by Django 4.2.5 on 2023-09-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='fact',
        ),
        migrations.AddField(
            model_name='sales',
            name='fact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='sales.salesrecord'),
        ),
    ]
