# Generated by Django 4.2.5 on 2023-09-24 15:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_options_alter_store_city_and_more'),
        ('categories', '0002_alter_category_options_alter_category_category_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='salesrecord',
            options={'verbose_name': 'Запись продаж', 'verbose_name_plural': 'Записи продаж'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_sales', to='categories.category', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Продажи в рублях'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_rub_promo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Акционные продажи в рублях'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_type',
            field=models.IntegerField(verbose_name='Тип продаж'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_units',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество единиц'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_units_promo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество акционных единиц'),
        ),
    ]
