# Generated by Django 4.2.5 on 2023-09-27 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('categories', '0001_initial'),
        ('sales', '0002_remove_salesrecord_fact_sales_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='sales.salesrecord')),
                ('fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_sales_records', to='sales.salesrecord')),
                ('sales_rub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rubs', to='sales.salesrecord')),
                ('sales_run_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_runs_promo', to='sales.salesrecord')),
                ('sales_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_types', to='sales.salesrecord')),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_unit', to='sales.salesrecord')),
                ('sales_units_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_unit_promo', to='sales.salesrecord')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sku_sales', to='categories.category', verbose_name='захэшированное id товара')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_store_sales', to='stores.store', verbose_name='захэшированное id магазина')),
            ],
        ),
    ]
