# Generated by Django 4.2.5 on 2023-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sales_import_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales_import',
        ),
    ]
