# Generated by Django 4.2.5 on 2023-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_delete_sales_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_units',
            field=models.IntegerField(verbose_name='число проданных товаров без признака промо'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sales_units_promo',
            field=models.IntegerField(verbose_name='число проданных товаров с признаком промо'),
        ),
    ]
