# Generated by Django 4.2.5 on 2023-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('type_format', models.IntegerField()),
                ('loc', models.IntegerField()),
                ('size', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
