# Generated by Django 4.2.5 on 2023-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(choices=[(0, 'НЕТ'), (1, 'ДА')], verbose_name='флаг активного магазина на данный момент'),
        ),
    ]
