# Generated by Django 4.2.5 on 2023-09-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('store',), 'verbose_name': 'Сводная таблица магазина', 'verbose_name_plural': 'Сводная таблица магазинов'},
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(null=True, verbose_name='id типа размера магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='stores.size'),
        ),
    ]
