# Generated by Django 4.2.5 on 2023-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('store',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=50, verbose_name='захэшированное id города'),
        ),
        migrations.AlterField(
            model_name='store',
            name='division',
            field=models.CharField(max_length=50, verbose_name='захэшированное id дивизиона'),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(verbose_name='флаг активного магазина на данный момент'),
        ),
        migrations.AlterField(
            model_name='store',
            name='loc',
            field=models.IntegerField(verbose_name='id тип локации/окружения магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.IntegerField(verbose_name='id типа размера магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store',
            field=models.CharField(max_length=50, verbose_name='захэшированное id магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type_format',
            field=models.IntegerField(verbose_name='id формата магазина'),
        ),
    ]
