# Generated by Django 4.2.5 on 2023-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='флаг активного магазина на данный момент'),
        ),
    ]
