swagger: '2.0'
info:
  title: LENTA API
  description: Предсказание временных рядом
  version: v1
host: 127.0.0.1:8080
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /auth/token/login/:
    post:
      operationId: auth_token_login_create
      description: Use this endpoint to obtain user authentication token.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/TokenCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/TokenCreate'
      tags:
      - auth
    parameters: []
  /auth/token/logout/:
    post:
      operationId: auth_token_logout_create
      description: Use this endpoint to logout user (remove user authentication token).
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - auth
    parameters: []
  /categories/:
    get:
      operationId: categories_list
      description: Вьюсет для товарной иерархии.
      parameters:
      - name: sku
        in: query
        description: sku
        required: false
        type: string
      - name: group__group
        in: query
        description: group__group
        required: false
        type: string
      - name: category__category
        in: query
        description: category__category
        required: false
        type: string
      - name: subcategory__subcategory
        in: query
        description: subcategory__subcategory
        required: false
        type: string
      - name: group
        in: query
        description: group
        required: false
        type: string
      - name: category
        in: query
        description: category
        required: false
        type: string
      - name: subcategory
        in: query
        description: subcategory
        required: false
        type: string
      - name: uom
        in: query
        description: uom
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Category'
      tags:
      - categories
    parameters: []
  /categories/{sku}/:
    get:
      operationId: categories_read
      description: Вьюсет для товарной иерархии.
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Category'
      tags:
      - categories
    parameters:
    - name: sku
      in: path
      required: true
      type: string
  /forecast/:
    get:
      operationId: forecast_list
      description: ''
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      - name: limit
        in: query
        description: Number of results to return per page.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/StoreForecast'
      tags:
      - forecast
    post:
      operationId: forecast_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/StoreForecastCreate'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/StoreForecastCreate'
      tags:
      - forecast
    parameters: []
  /sales/:
    get:
      operationId: sales_list
      description: |-
        Переопределенный метод для GET запроса
        на получение списка объектов Sales.
      parameters:
      - name: store
        in: query
        description: store
        required: false
        type: string
      - name: sku
        in: query
        description: sku
        required: false
        type: string
      - name: date
        in: query
        description: date
        required: false
        type: string
      - name: sales_type
        in: query
        description: sales_type
        required: false
        type: string
      - name: sales_units
        in: query
        description: sales_units
        required: false
        type: string
      - name: sales_units_promo
        in: query
        description: sales_units_promo
        required: false
        type: string
      - name: sales_rub
        in: query
        description: sales_rub
        required: false
        type: string
      - name: sales_run_promo
        in: query
        description: sales_run_promo
        required: false
        type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Sales'
      tags:
      - sales
    post:
      operationId: sales_create
      description: Функция создания категории.
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/CreateSales'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/CreateSales'
      tags:
      - sales
    parameters: []
  /sales/{store}/:
    get:
      operationId: sales_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Sales'
      tags:
      - sales
    parameters:
    - name: store
      in: path
      required: true
      type: string
  /shops/:
    get:
      operationId: shops_list
      description: Функция отображения списко магазинов.
      parameters:
      - name: store
        in: query
        description: хэш ID
        required: false
        type: string
      - name: city
        in: query
        description: city
        required: false
        type: string
      - name: division
        in: query
        description: division
        required: false
        type: string
      - name: type_format
        in: query
        description: type_format
        required: false
        type: string
      - name: loc
        in: query
        description: loc
        required: false
        type: string
      - name: size
        in: query
        description: size
        required: false
        type: string
      - name: is_active
        in: query
        description: is_active
        required: false
        type: string
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      - name: limit
        in: query
        description: Number of results to return per page.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Store'
      tags:
      - shops
    parameters: []
  /shops/{store}/:
    get:
      operationId: shops_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Store'
      tags:
      - shops
    parameters:
    - name: store
      in: path
      required: true
      type: string
  /users/login-with-code/:
    post:
      operationId: users_login-with-code_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/LoginWithCode'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/LoginWithCode'
      tags:
      - users
    parameters: []
  /users/reset-password/:
    post:
      operationId: users_reset-password_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordResetRequest'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetRequest'
      tags:
      - users
    parameters: []
definitions:
  TokenCreate:
    type: object
    properties:
      password:
        title: Password
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        minLength: 1
  Category:
    required:
    - sku
    - group
    - category
    - subcategory
    - uom
    type: object
    properties:
      sku:
        title: Захэшированное id товара
        type: string
        maxLength: 50
        minLength: 1
      group:
        title: Group
        type: integer
      category:
        title: Category
        type: integer
      subcategory:
        title: Subcategory
        type: integer
      uom:
        title: Маркер, обозначающий продаётся товар на вес или в ШТ
        type: integer
        enum:
        - штука
        - вес
  StoreForecast:
    required:
    - store
    - sku
    - forecast_date
    type: object
    properties:
      store:
        title: Store
        type: string
        minLength: 1
      sku:
        title: Sku
        type: string
        minLength: 1
      forecast_date:
        title: Дата прогноза
        type: string
        format: date
      forecast:
        title: Forecast
        type: string
        readOnly: true
  DailySalesForecast:
    required:
    - date
    - target
    type: object
    properties:
      date:
        title: Дата(день)
        type: string
        format: date
      target:
        title: Спрос в ШТ.
        type: integer
  StoreForecastCreate:
    required:
    - store
    - forecast_date
    - sku
    - sales_units
    type: object
    properties:
      store:
        title: Store
        type: string
        minLength: 1
      forecast_date:
        title: Дата прогноза
        type: string
        format: date
      sku:
        title: Sku
        type: string
        minLength: 1
      sales_units:
        type: array
        items:
          $ref: '#/definitions/DailySalesForecast'
  SalesRecordSerialazier:
    required:
    - date
    - sales_type
    - sales_units
    - sales_units_promo
    - sales_rub
    - sales_run_promo
    type: object
    properties:
      date:
        title: Date
        type: string
        format: date
      sales_type:
        title: Sales type
        type: integer
      sales_units:
        title: Sales units
        type: integer
      sales_units_promo:
        title: Sales units promo
        type: integer
      sales_rub:
        title: Sales rub
        type: string
        format: decimal
      sales_run_promo:
        title: Sales run promo
        type: string
        format: decimal
  Sales:
    required:
    - fact
    type: object
    properties:
      store:
        title: Store
        type: string
        readOnly: true
      sku:
        title: Sku
        type: string
        readOnly: true
      fact:
        $ref: '#/definitions/SalesRecordSerialazier'
  CreateSales:
    required:
    - store
    - sku
    - fact
    type: object
    properties:
      store:
        title: Store
        type: string
        minLength: 1
      sku:
        title: Sku
        type: string
        minLength: 1
      fact:
        $ref: '#/definitions/SalesRecordSerialazier'
  Store:
    required:
    - city
    - division
    - type_format
    - loc
    - is_active
    type: object
    properties:
      store:
        title: Store
        type: string
        readOnly: true
      city:
        title: Захэшированное id города
        type: string
        maxLength: 50
        minLength: 1
      division:
        title: Захэшированное id дивизиона
        type: string
        maxLength: 50
        minLength: 1
      type_format:
        title: Id формата магазина
        type: integer
      loc:
        title: Id тип локации/окружения магазина
        type: integer
      size:
        title: Id типа размера магазина
        type: integer
        x-nullable: true
      is_active:
        title: Флаг активного магазина на данный момент
        type: boolean
  LoginWithCode:
    required:
    - email
    - code
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      code:
        title: Code
        type: string
        minLength: 1
  PasswordResetRequest:
    required:
    - email
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
